image:
  repository: postgres
  tag: "17-alpine"

containerPort: 5432

env:
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: postgres-postgres
        key: POSTGRES_USER
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-postgres
        key: POSTGRES_PASSWORD
  - name: POSTGRES_DB
    valueFrom:
      secretKeyRef:
        name: postgres-postgres
        key: POSTGRES_DB

readinessProbe:
  exec:
    command: ["pg_isready", "-U", "postgres"]
  initialDelaySeconds: 5
  periodSeconds: 10

storage:
  persistent: false
  size: 1Gi

service:
  port: 5432
